version: '3'
services:
  backend:
    #image: yangre:v7
    build: .
    volumes:
      - ./data:/home
  frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/usr/share/nginx/html:ro
    depends_on:
      - backend
    ports:
      - 80:80